"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "answers",
      [
        {
          title: "Accumulation, Markup, Distribution & Decline",
          question_id: 1,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Introduction, Growth, Maturity & Decline",
          question_id: 1,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Introduction, Maturity, Distribution & Decline",
          question_id: 1,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Accumulation, Growth, Markup & Distribution",
          question_id: 1,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Decline",
          question_id: 2,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Markup",
          question_id: 2,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Distribution",
          question_id: 2,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "Accumulation",
          question_id: 2,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Bull Market",
          question_id: 3,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Bear Market",
          question_id: 3,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 4,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 4,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "1 - 3 years",
          question_id: 5,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "4 - 10 years",
          question_id: 5,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "10 - 20 years",
          question_id: 5,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 5,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 6,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 6,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Accumulation",
          question_id: 7,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Markup",
          question_id: 7,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Distribution",
          question_id: 7,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Decline",
          question_id: 7,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "True",
          question_id: 8,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 8,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "2008 mortgage bubble",
          question_id: 9,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "2001 dot-com bubble",
          question_id: 9,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "1987 black Monday",
          question_id: 9,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 9,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "True",
          question_id: 10,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 10,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Diversification",
          question_id: 11,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Stable Growth",
          question_id: 11,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Long Term Returns",
          question_id: 11,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 11,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "$200",
          question_id: 12,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "$150",
          question_id: 12,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "$161",
          question_id: 12,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "$110",
          question_id: 12,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "NASDAQ",
          question_id: 13,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "S&P 500",
          question_id: 13,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "NYSE",
          question_id: 13,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 13,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 14,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 14,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 15,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 15,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "ETFs",
          question_id: 16,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Stocks",
          question_id: 16,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Cryptocurrencies ",
          question_id: 16,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 16,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "By including the most expensive stocks from the sector",
          question_id: 17,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "By including the most profitable stocks from the sector",
          question_id: 17,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "By including the most relevant stocks from the sector",
          question_id: 17,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 17,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Commission",
          question_id: 18,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Expense Ratio",
          question_id: 18,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Premium",
          question_id: 18,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Discount",
          question_id: 18,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 19,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 19,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Apple, Amazon & Coke Cola",
          question_id: 20,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "AT&T, Uber & General Electric",
          question_id: 20,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Google, Microsoft & Apple",
          question_id: 20,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "Walmart, Wells Fargo & Tesla",
          question_id: 20,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "A form of cash",
          question_id: 21,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "A good or service",
          question_id: 21,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "A piece of ownership in a company",
          question_id: 21,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 21,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Dividend payments",
          question_id: 22,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Capital Growth",
          question_id: 22,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Ability to vote and influence company decisions",
          question_id: 22,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 22,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "Low debt-to-equity ratio",
          question_id: 23,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "No dilution of control",
          question_id: 23,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 23,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 23,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Preferred Stockholder",
          question_id: 24,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Common Stockholder",
          question_id: 24,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Dividends",
          question_id: 25,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Voting Rights",
          question_id: 25,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Growth Rate",
          question_id: 25,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 25,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "1%",
          question_id: 26,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "0.01%",
          question_id: 26,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "10%",
          question_id: 26,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "0.1%",
          question_id: 26,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Buy and Sell",
          question_id: 27,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Sell",
          question_id: 27,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Buy and Hold",
          question_id: 27,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 27,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "0.0001%",
          question_id: 28,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "0.0002%",
          question_id: 28,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "0.0003%",
          question_id: 28,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "0.0004%",
          question_id: 28,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 29,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 29,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Investor speculation",
          question_id: 30,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Competitors",
          question_id: 30,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Earnings and Valuation",
          question_id: 30,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 30,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "A payment made by the shareholders to a company",
          question_id: 31,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "A payment made by the a company to its vendors",
          question_id: 31,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "A payment received by the shareholder from a company",
          question_id: 31,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 31,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 32,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 32,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "DRAP",
          question_id: 33,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "DROP",
          question_id: 33,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "DRIP",
          question_id: 33,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 33,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title:
            "They reinvest earning back into the company to accelerate growth",
          question_id: 34,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "They don’t make profits",
          question_id: 34,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "They don’t have liquid cash",
          question_id: 34,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "They have a high stock price",
          question_id: 34,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Annually",
          question_id: 35,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Semiannually",
          question_id: 35,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Quarterly",
          question_id: 35,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 35,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "Dividends enhance portfolios",
          question_id: 36,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Steady flow of income for investors",
          question_id: 36,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Positive aspect for long term investments",
          question_id: 36,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 36,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "True",
          question_id: 37,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 37,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Stays the same",
          question_id: 38,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Decreases",
          question_id: 38,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Increases",
          question_id: 38,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 38,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "True",
          question_id: 39,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 39,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "1.34%",
          question_id: 40,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "3%",
          question_id: 40,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "2.27%",
          question_id: 40,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "2.5%",
          question_id: 40,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "When a company raises capital",
          question_id: 41,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "When a company issues stock for the first time",
          question_id: 41,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "When a company becomes profitable",
          question_id: 41,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 41,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Dutch East India Company in 1602",
          question_id: 42,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "General Electric in 1896",
          question_id: 42,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Apple Inc. in 1980",
          question_id: 42,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Ford in 1956",
          question_id: 42,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "When they have a unique product offering",
          question_id: 43,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "When their private valuation hits $1 billion",
          question_id: 43,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "When their public valuation hits $10 billion",
          question_id: 43,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "When they turn a profit of $1 billion",
          question_id: 43,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "2001",
          question_id: 44,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "2008",
          question_id: 44,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "2020",
          question_id: 44,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 44,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 45,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 45,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 46,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 46,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Startups",
          question_id: 47,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Well known companies",
          question_id: 47,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Innovative companies",
          question_id: 47,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 47,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Direct listing IPO",
          question_id: 48,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Underwriter",
          question_id: 48,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 49,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 49,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "True",
          question_id: 50,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 50,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "A place where goods are bought and sold",
          question_id: 51,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "A place where services are bought and sold",
          question_id: 51,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "A place where securities are bought and sold",
          question_id: 51,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 51,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "New York Stock Exchange",
          question_id: 52,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "NASDAQ Stock Market",
          question_id: 52,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Tokyo Stock Exchange",
          question_id: 52,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Nigerian Stock Exchange",
          question_id: 52,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "1792",
          question_id: 53,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "1790",
          question_id: 53,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "1768",
          question_id: 53,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "1798",
          question_id: 53,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Retail Investors",
          question_id: 54,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Institutional Investors",
          question_id: 54,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Day Traders",
          question_id: 54,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 54,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Day Traders",
          question_id: 55,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Hedge Funds",
          question_id: 55,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Insurance Companies",
          question_id: 55,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Private Equity Firms",
          question_id: 55,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 56,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 56,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Bad publicity",
          question_id: 57,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Investor Confidence",
          question_id: 57,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Changes in Technology",
          question_id: 57,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 57,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "Over a phone call",
          question_id: 58,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "On a web interface",
          question_id: 58,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "On the Trading floor",
          question_id: 58,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 58,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "$2 million",
          question_id: 59,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "$4 million",
          question_id: 59,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "$6 million",
          question_id: 59,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "$8 million",
          question_id: 59,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 60,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 60,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Investing in different types of assets",
          question_id: 61,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Investing in stocks",
          question_id: 61,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Investing in cryptocurrencies",
          question_id: 61,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Investing in bonds",
          question_id: 61,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 62,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 62,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Unsystematic Risk",
          question_id: 63,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Systematic Risk",
          question_id: 63,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Investment Risk",
          question_id: 63,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 63,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 64,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 64,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Stocks",
          question_id: 65,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "ETFs",
          question_id: 65,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Bonds",
          question_id: 65,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Cryptocurrencies",
          question_id: 65,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Multiple stocks",
          question_id: 66,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Multiple Asset classes",
          question_id: 66,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Multiple Cryptocurrencies",
          question_id: 66,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 66,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 67,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 67,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Risky",
          question_id: 68,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Diverse",
          question_id: 68,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "That tracks the performance of a stock",
          question_id: 69,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "That tracks the performance of a specific market",
          question_id: 69,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "That tracks the performance of a specific sector",
          question_id: 69,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 69,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title:
            "An index that tracks the 500 most innovative publicly traded companies in the US",
          question_id: 70,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title:
            "An index that tracks the 500 most profitable publicly traded companies in the US",
          question_id: 70,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title:
            "An index that tracks the 500 largest publicly traded companies in the US",
          question_id: 70,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "An index that tracks fortune 500 companies",
          question_id: 70,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "United States",
          question_id: 71,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "United Kingdom",
          question_id: 71,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "United Arab Emirates",
          question_id: 71,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 71,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 72,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 72,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "ADX general index",
          question_id: 73,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "S&P500",
          question_id: 73,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Vanguard ETF",
          question_id: 73,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 73,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 74,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 74,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title:
            "Average stock price growth of 40% registered by several stock exchanges",
          question_id: 75,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title:
            "Average stock price growth of 100% registered by one stock exchange",
          question_id: 75,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title:
            "Average stock price growth of 50% registered by all stock exchanges",
          question_id: 75,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title:
            "Average stock price growth of 20% registered by several stock exchanges",
          question_id: 75,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "1990-1999",
          question_id: 76,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "2000-2008",
          question_id: 76,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "2009-2020",
          question_id: 76,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 76,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Weak Economy, Increase in IPOs & Increase in GDP",
          question_id: 77,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Strong Economy, Low Investor Confidence & Decrease in IPOs",
          question_id: 77,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Weak Economy, High Unemployment Rates & Decrease in GDP",
          question_id: 77,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 77,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Bullish Markets",
          question_id: 78,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Bearish Markets",
          question_id: 78,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Consumer Staples Stocks",
          question_id: 79,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Tech Stocks",
          question_id: 79,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Oil and Energy Stocks",
          question_id: 79,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Real Estate Stocks",
          question_id: 79,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 80,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 80,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 81,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 81,
          answer_order: 1,
          correct_answer: false,
        },
        // Blog10
        {
          title: "Bahrain",
          question_id: 82,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Qatar",
          question_id: 82,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Saudi Arabia",
          question_id: 82,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "United Arab Emirates",
          question_id: 82,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Oil & Gas",
          question_id: 83,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Real Estate",
          question_id: 83,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Technology",
          question_id: 83,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Financial Services",
          question_id: 83,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Digital Projects",
          question_id: 84,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Hospitality Projects",
          question_id: 84,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Real Estate Projects",
          question_id: 84,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Healthcare Projects",
          question_id: 84,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "GCC",
          question_id: 85,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Middle East",
          question_id: 85,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Asia",
          question_id: 85,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "World",
          question_id: 85,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "Tadawul General Index",
          question_id: 86,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Tadawul Index",
          question_id: 86,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Tadawul All Shares Index",
          question_id: 86,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 86,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "219.56%",
          question_id: 87,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "389.40%",
          question_id: 87,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "567.91%",
          question_id: 87,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "890.54%",
          question_id: 87,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "2 billion",
          question_id: 88,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "5.5 billion",
          question_id: 88,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "9.35 billion",
          question_id: 88,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "10 billion",
          question_id: 88,
          answer_order: 3,
          correct_answer: false,
        },
        // Blog 11
        {
          title: "Dubai",
          question_id: 89,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Sharjah",
          question_id: 89,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Ajman",
          question_id: 89,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Abu Dhabi",
          question_id: 89,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "1995",
          question_id: 90,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "2000",
          question_id: 90,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "2005",
          question_id: 90,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "2010",
          question_id: 90,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "ADX general index",
          question_id: 91,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "S&P 500",
          question_id: 91,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "NBAD Oneshare Dow Jones UAE 25",
          question_id: 91,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 91,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Technology, Energy, Banks & Manufacturing",
          question_id: 92,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Banks, Telecommunications, Energy & Real Estate",
          question_id: 92,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Real Estate, Energy, Technology and Manufacturing",
          question_id: 92,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Banks, Technology, Real Estate and Telecommunications",
          question_id: 92,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 93,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 93,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Large Corporations",
          question_id: 94,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Foreign Corporation",
          question_id: 94,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Family Owned Business",
          question_id: 94,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 94,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "$564 million",
          question_id: 95,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "$778 million",
          question_id: 95,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "$851 million",
          question_id: 95,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "$1.01 million",
          question_id: 95,
          answer_order: 3,
          correct_answer: false,
        },
        // Blog 12
        {
          title: "SEC",
          question_id: 96,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "FCA",
          question_id: 96,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "CMA",
          question_id: 96,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "SCA",
          question_id: 96,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "Energy",
          question_id: 97,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Financial",
          question_id: 97,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Real Estate",
          question_id: 97,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Telecommunications",
          question_id: 97,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "AED 159 billion",
          question_id: 98,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "AED 294 billion",
          question_id: 98,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "AED 378 billion",
          question_id: 98,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "AED 433 billion",
          question_id: 98,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Government Owned",
          question_id: 99,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Emerging Markets",
          question_id: 99,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Developed Markets",
          question_id: 99,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 99,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "54",
          question_id: 100,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "59",
          question_id: 100,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "61",
          question_id: 100,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "66",
          question_id: 100,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "10%",
          question_id: 101,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "15%",
          question_id: 101,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "20%",
          question_id: 101,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "25%",
          question_id: 101,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "2000",
          question_id: 102,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "2002",
          question_id: 102,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "2001",
          question_id: 102,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "2003",
          question_id: 102,
          answer_order: 3,
          correct_answer: false,
        },
        // Blog 13
        {
          title: "Positive Correlation",
          question_id: 103,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Negative Correlation",
          question_id: 103,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "No Correlation",
          question_id: 103,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 103,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "Uber and Lyft",
          question_id: 104,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Google and Coke-Cola",
          question_id: 104,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Apple and General Electric",
          question_id: 104,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Tesla and Wells Fargo",
          question_id: 104,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 105,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 105,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Lack of diversification",
          question_id: 106,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Diversification",
          question_id: 106,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Doesn’t represent anything",
          question_id: 106,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 106,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "1.0",
          question_id: 107,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "0",
          question_id: 107,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "-1.0",
          question_id: 107,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "0.5",
          question_id: 107,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 108,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 108,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Assets with positive correlation",
          question_id: 109,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Assets with negative correlation",
          question_id: 109,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Assets with no correlation",
          question_id: 109,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 109,
          answer_order: 3,
          correct_answer: false,
        },
        // Blog 14
        {
          title: "1847",
          question_id: 110,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "1850",
          question_id: 110,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "1857",
          question_id: 110,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "1863",
          question_id: 110,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Texas",
          question_id: 111,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Ohio",
          question_id: 111,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Pennsylvania",
          question_id: 111,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "California",
          question_id: 111,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "To produce as much as oil as possible",
          question_id: 112,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "To try and maximise the price of oil",
          question_id: 112,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title:
            "To ensure stabilization of oil prices in the international markets",
          question_id: 112,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 112,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "India",
          question_id: 113,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "United States",
          question_id: 113,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "China",
          question_id: 113,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Russia",
          question_id: 113,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "20%",
          question_id: 114,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "30%",
          question_id: 114,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "40%",
          question_id: 114,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "50%",
          question_id: 114,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 115,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 115,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Socio-Political Factors",
          question_id: 116,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Economic Factors",
          question_id: 116,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Environmental Factors",
          question_id: 116,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 116,
          answer_order: 3,
          correct_answer: true,
        },
        // Blog15
        {
          title: "True",
          question_id: 117,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 117,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "54%",
          question_id: 118,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "67%",
          question_id: 118,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "73%",
          question_id: 118,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "87%",
          question_id: 118,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "$66.7",
          question_id: 119,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "$67.1",
          question_id: 119,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "$67.8",
          question_id: 119,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "$68.4",
          question_id: 119,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "India",
          question_id: 120,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "United States",
          question_id: 120,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Pakistan",
          question_id: 120,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Nigeria",
          question_id: 120,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "True",
          question_id: 121,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 121,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Tourism",
          question_id: 122,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Tax Initiatives",
          question_id: 122,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Digital Economies",
          question_id: 122,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 122,
          answer_order: 3,
          correct_answer: true,
        },
        // Blog 16
        {
          title: "Infant mortality rate halved and life expectancy rose",
          question_id: 123,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Average literacy rate and employment rate rose",
          question_id: 123,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 123,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 123,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Geo-political",
          question_id: 124,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Alternative Energy",
          question_id: 124,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "OPEC",
          question_id: 124,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "All of the above",
          question_id: 124,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "True",
          question_id: 125,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 125,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Positively",
          question_id: 126,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Negatively ",
          question_id: 126,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Doesn’t impact them at all",
          question_id: 126,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 126,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 127,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 127,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Brazil",
          question_id: 128,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Canada",
          question_id: 128,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "France",
          question_id: 128,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "Iraq",
          question_id: 128,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Prices are still too high",
          question_id: 129,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title:
            "Don’t have enough financial power to take advantage of the situation",
          question_id: 129,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Travel restrictions and lockdowns",
          question_id: 129,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 129,
          answer_order: 3,
          correct_answer: false,
        },
        // Blog 17
        {
          title: "A shell company with no operations",
          question_id: 130,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "A technology company",
          question_id: 130,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "A company with a high profits",
          question_id: 130,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 130,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 131,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 131,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "It could affect SPAC’s share price",
          question_id: 132,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Investor speculation could affect acquisition price",
          question_id: 132,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Scare away investors",
          question_id: 132,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 132,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 133,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "False",
          question_id: 133,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "True",
          question_id: 134,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 134,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Past few years",
          question_id: 135,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Past 5 years",
          question_id: 135,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Past decades",
          question_id: 135,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Past few decades",
          question_id: 135,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "$4 billion",
          question_id: 136,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "$8 billion",
          question_id: 136,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "$12 billion",
          question_id: 136,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "$16 billion",
          question_id: 136,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Poor compared to traditional IPOs",
          question_id: 137,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Better than traditional IPOs",
          question_id: 137,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Similar to traditional IPOs",
          question_id: 137,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 137,
          answer_order: 3,
          correct_answer: false,
        },
        // Blog 18
        {
          title: "True",
          question_id: 138,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 138,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Poor corporate governance",
          question_id: 139,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Chaotic management",
          question_id: 139,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Earning report and IPOs",
          question_id: 139,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "Political unrest, Pandemics & Trade wars",
          question_id: 139,
          answer_order: 3,
          correct_answer: true,
        },
        {
          title: "Sadness",
          question_id: 140,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Jealousy",
          question_id: 140,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Excitement and nervousness",
          question_id: 140,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "All of the above",
          question_id: 140,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Diversification",
          question_id: 141,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "Smart Investments",
          question_id: 141,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Not investing",
          question_id: 141,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 141,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "True",
          question_id: 142,
          answer_order: 0,
          correct_answer: true,
        },
        {
          title: "False",
          question_id: 142,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Never had a downturn",
          question_id: 143,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Never recovered after a downturn",
          question_id: 143,
          answer_order: 1,
          correct_answer: false,
        },
        {
          title: "Recovered after a downturn",
          question_id: 143,
          answer_order: 2,
          correct_answer: true,
        },
        {
          title: "None of the above",
          question_id: 143,
          answer_order: 3,
          correct_answer: false,
        },
        {
          title: "Sell",
          question_id: 144,
          answer_order: 0,
          correct_answer: false,
        },
        {
          title: "Buy",
          question_id: 144,
          answer_order: 1,
          correct_answer: true,
        },
        {
          title: "Hold",
          question_id: 144,
          answer_order: 2,
          correct_answer: false,
        },
        {
          title: "None of the above",
          question_id: 144,
          answer_order: 3,
          correct_answer: false,
        },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.bulkDelete('People', null, {});
    */
  },
};
